var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/museum/page.js")
R.c("server/chunks/ssr/_3146e964._.js")
R.c("server/chunks/ssr/[root-of-the-server]__5d5aaa26._.js")
R.c("server/chunks/ssr/_058f162a._.js")
R.c("server/chunks/ssr/[root-of-the-server]__3237281e._.js")
R.c("server/chunks/ssr/[root-of-the-server]__655f8d11._.js")
R.c("server/chunks/ssr/[root-of-the-server]__8ecbddb6._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/_d8c426de._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_museum_page_actions_0ce13161.js")
R.m(7841)
module.exports=R.m(7841).exports
