var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/about/page.js")
R.c("server/chunks/ssr/_f07c61a9._.js")
R.c("server/chunks/ssr/[root-of-the-server]__5d5aaa26._.js")
R.c("server/chunks/ssr/_de582a75._.js")
R.c("server/chunks/ssr/[root-of-the-server]__3237281e._.js")
R.c("server/chunks/ssr/[root-of-the-server]__655f8d11._.js")
R.c("server/chunks/ssr/[root-of-the-server]__8ecbddb6._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/_d8c426de._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_about_page_actions_6fff35e4.js")
R.m(691)
module.exports=R.m(691).exports
